pub(crate) const CODES: [[Option<&'static str>; 256]; 11] = [
    [
        None,
        Some("AMD"),
        Some("AMI"),
        Some("Fairchild"),
        Some("Fujitsu"),
        Some("GTE"),
        Some("Harris"),
        Some("Hitachi"),
        Some("Inmos"),
        Some("Intel"),
        Some("I.T.T."),
        Some("Intersil"),
        Some("Monolithic Memories"),
        Some("Mostek"),
        Some("Freescale (Motorola)"),
        Some("National"),
        Some("NEC"),
        Some("RCA"),
        Some("Raytheon"),
        Some("Conexant (Rockwell)"),
        Some("Seeq"),
        Some("NXP (Philips)"),
        Some("Synertek"),
        Some("Texas Instruments"),
        Some("Toshiba"),
        Some("Xicor"),
        Some("Zilog"),
        Some("Eurotechnique"),
        Some("Mitsubishi"),
        Some("Lucent (AT&T)"),
        Some("Exel"),
        Some("Atmel"),
        Some("STMicroelectronics"),
        Some("Lattice Semi."),
        Some("NCR"),
        Some("Wafer Scale Integration"),
        Some("IBM"),
        Some("Tristar"),
        Some("Visic"),
        Some("Intl. CMOS Technology"),
        Some("SSSI"),
        Some("MicrochipTechnology"),
        Some("Ricoh Ltd"),
        Some("VLSI"),
        Some("Micron Technology"),
        Some("SK Hynix"),
        Some("OKI Semiconductor"),
        Some("ACTEL"),
        Some("Sharp"),
        Some("Catalyst"),
        Some("Panasonic"),
        Some("IDT"),
        Some("Cypress"),
        Some("DEC"),
        Some("LSI Logic"),
        Some("Zarlink (Plessey)"),
        Some("UTMC"),
        Some("Thinking Machine"),
        Some("Thomson CSF"),
        Some("Integrated CMOS (Vertex)"),
        Some("Honeywell"),
        Some("Tektronix"),
        Some("Oracle Corporation"),
        Some("Silicon Storage Technology"),
        Some("ProMos/Mosel Vitelic"),
        Some("Infineon (Siemens)"),
        Some("Macronix"),
        Some("Xerox"),
        Some("Plus Logic"),
        Some("Western Digital Technologies Inc"),
        Some("Elan Circuit Tech."),
        Some("European Silicon Str."),
        Some("Apple Computer"),
        Some("Xilinx"),
        Some("Compaq"),
        Some("Protocol Engines"),
        Some("SCI"),
        Some("Seiko Instruments"),
        Some("Samsung"),
        Some("I3 Design System"),
        Some("Klic"),
        Some("Crosspoint Solutions"),
        Some("Alliance Semiconductor"),
        Some("Tandem"),
        Some("Hewlett-Packard"),
        Some("Integrated Silicon Solutions"),
        Some("Brooktree"),
        Some("New Media"),
        Some("MHS Electronic"),
        Some("Performance Semi."),
        Some("Winbond Electronic"),
        Some("Kawasaki Steel"),
        Some("Bright Micro"),
        Some("TECMAR"),
        Some("Exar"),
        Some("PCMCIA"),
        Some("LG Semi (Goldstar)"),
        Some("Northern Telecom"),
        Some("Sanyo"),
        Some("Array Microsystems"),
        Some("Crystal Semiconductor"),
        Some("Analog Devices"),
        Some("PMC-Sierra"),
        Some("Asparix"),
        Some("Convex Computer"),
        Some("Quality Semiconductor"),
        Some("Nimbus Technology"),
        Some("Transwitch"),
        Some("Micronas (ITT Intermetall)"),
        Some("Cannon"),
        Some("Altera"),
        Some("NEXCOM"),
        Some("Qualcomm"),
        Some("Sony"),
        Some("Cray Research"),
        Some("AMS(Austria Micro)"),
        Some("Vitesse"),
        Some("Aster Electronics"),
        Some("Bay Networks (Synoptic)"),
        Some("Zentrum/ZMD"),
        Some("TRW"),
        Some("Thesys"),
        Some("Solbourne Computer"),
        Some("Allied-Signal"),
        Some("Dialog Semiconductor"),
        Some("Media Vision"),
        Some("Numonyx Corporation"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Cirrus Logic"),
        Some("National Instruments"),
        Some("ILC Data Device"),
        Some("Alcatel Mietec"),
        Some("Micro Linear"),
        Some("Univ. of NC"),
        Some("JTAG Technologies"),
        Some("BAE Systems (Loral)"),
        Some("Nchip"),
        Some("Galileo Tech"),
        Some("Bestlink Systems"),
        Some("Graychip"),
        Some("GENNUM"),
        Some("VideoLogic"),
        Some("Robert Bosch"),
        Some("Chip Express"),
        Some("DATARAM"),
        Some("United Microelectronics Corp"),
        Some("TCSI"),
        Some("Smart Modular"),
        Some("Hughes Aircraft"),
        Some("Lanstar Semiconductor"),
        Some("Qlogic"),
        Some("Kingston"),
        Some("Music Semi"),
        Some("Ericsson Components"),
        Some("SpaSE"),
        Some("Eon Silicon Devices"),
        Some("Integrated Silicon Solution (ISSI)"),
        Some("DoD"),
        Some("Integ. Memories Tech."),
        Some("Corollary Inc"),
        Some("Dallas Semiconductor"),
        Some("Omnivision"),
        Some("EIV(Switzerland)"),
        Some("Novatel Wireless"),
        Some("Zarlink (Mitel)"),
        Some("Clearpoint"),
        Some("Cabletron"),
        Some("STEC (Silicon Tech)"),
        Some("Vanguard"),
        Some("Hagiwara Sys-Com"),
        Some("Vantis"),
        Some("Celestica"),
        Some("Century"),
        Some("Hal Computers"),
        Some("Rohm Company Ltd"),
        Some("Juniper Networks"),
        Some("Libit Signal Processing"),
        Some("Mushkin Enhanced Memory"),
        Some("Tundra Semiconductor"),
        Some("Adaptec Inc"),
        Some("LightSpeed Semi."),
        Some("ZSP Corp"),
        Some("AMIC Technology"),
        Some("Adobe Systems"),
        Some("Dynachip"),
        Some("PNY Technologies Inc"),
        Some("Newport Digital"),
        Some("MMC Networks"),
        Some("T Square"),
        Some("Seiko Epson"),
        Some("Broadcom"),
        Some("Viking Components"),
        Some("V3 Semiconductor"),
        Some("Flextronics (Orbit Semiconductor)"),
        Some("Suwa Electronics"),
        Some("Transmeta"),
        Some("Micron CMS"),
        None,
        Some("Enhance 3000 Inc"),
        Some("Tower Semiconductor"),
        Some("CPU Design"),
        Some("Price Point"),
        Some("Maxim Integrated Product"),
        Some("Tellabs"),
        Some("Centaur Technology"),
        Some("Unigen Corporation"),
        Some("Transcend Information"),
        Some("Memory Card Technology"),
        Some("CKD Corporation Ltd"),
        Some("Capital Instruments Inc"),
        Some("Aica Kogyo Ltd"),
        Some("Linvex Technology"),
        Some("MSC Vertriebs GmbH"),
        Some("AKM Company Ltd"),
        Some("Dynamem Inc"),
        Some("NERA ASA"),
        Some("GSI Technology"),
        Some("Dane-Elec (C Memory)"),
        Some("Acorn Computers"),
        Some("Lara Technology"),
        Some("Oak Technology Inc"),
        Some("Itec Memory"),
        Some("Tanisys Technology"),
        Some("Truevision"),
        Some("Wintec Industries"),
        Some("Super PC Memory"),
        Some("MGV Memory"),
        Some("Galvantech"),
        Some("Gadzoox Networks"),
        Some("Multi Dimensional Cons."),
        Some("GateField"),
        Some("Integrated Memory System"),
        Some("Triscend"),
        Some("XaQti"),
        Some("Goldenram"),
        Some("Clear Logic"),
        Some("Cimaron Communications"),
        Some("Nippon Steel Semi. Corp"),
        Some("Advantage Memory"),
        Some("AMCC"),
        Some("LeCroy"),
        Some("Yamaha Corporation"),
        Some("Digital Microwave"),
        Some("NetLogic Microsystems"),
        Some("MIMOS Semiconductor"),
        Some("Advanced Fibre"),
        Some("BF Goodrich Data."),
        Some("Epigram"),
        Some("Acbel Polytech Inc"),
        Some("Apacer Technology"),
        Some("Admor Memory"),
        Some("FOXCONN"),
        Some("Quadratics Superconductor"),
        Some("3COM"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Camintonn Corporation"),
        Some("ISOA Incorporated"),
        Some("Agate Semiconductor"),
        Some("ADMtek Incorporated"),
        Some("HYPERTEC"),
        Some("Adhoc Technologies"),
        Some("MOSAID Technologies"),
        Some("Ardent Technologies"),
        Some("Switchcore"),
        Some("Cisco Systems Inc"),
        Some("Allayer Technologies"),
        Some("WorkX AG (Wichman)"),
        Some("Oasis Semiconductor"),
        Some("Novanet Semiconductor"),
        Some("E-M Solutions"),
        Some("Power General"),
        Some("Advanced Hardware Arch."),
        Some("Inova Semiconductors GmbH"),
        Some("Telocity"),
        Some("Delkin Devices"),
        Some("Symagery Microsystems"),
        Some("C-Port Corporation"),
        Some("SiberCore Technologies"),
        Some("Southland Microsystems"),
        Some("Malleable Technologies"),
        Some("Kendin Communications"),
        Some("Great Technology Microcomputer"),
        Some("Sanmina Corporation"),
        Some("HADCO Corporation"),
        Some("Corsair"),
        Some("Actrans System Inc"),
        Some("ALPHA Technologies"),
        Some("Silicon Laboratories Inc (Cygnal)"),
        Some("Artesyn Technologies"),
        Some("Align Manufacturing"),
        Some("Peregrine Semiconductor"),
        Some("Chameleon Systems"),
        Some("Aplus Flash Technology"),
        Some("MIPS Technologies"),
        Some("Chrysalis ITS"),
        Some("ADTEC Corporation"),
        Some("Kentron Technologies"),
        Some("Win Technologies"),
        Some("Tezzaron Semiconductor"),
        Some("Extreme Packet Devices"),
        Some("RF Micro Devices"),
        Some("Siemens AG"),
        Some("Sarnoff Corporation"),
        Some("Itautec SA"),
        Some("Radiata Inc"),
        Some("Benchmark Elect. (AVEX)"),
        Some("Legend"),
        Some("SpecTek Incorporated"),
        Some("Hi/fn"),
        Some("Enikia Incorporated"),
        Some("SwitchOn Networks"),
        Some("AANetcom Incorporated"),
        Some("Micro Memory Bank"),
        Some("ESS Technology"),
        Some("Virata Corporation"),
        Some("Excess Bandwidth"),
        Some("West Bay Semiconductor"),
        Some("DSP Group"),
        Some("Newport Communications"),
        Some("Chip2Chip Incorporated"),
        Some("Phobos Corporation"),
        Some("Intellitech Corporation"),
        Some("Nordic VLSI ASA"),
        Some("Ishoni Networks"),
        Some("Silicon Spice"),
        Some("Alchemy Semiconductor"),
        Some("Agilent Technologies"),
        Some("Centillium Communications"),
        Some("W.L. Gore"),
        Some("HanBit Electronics"),
        Some("GlobeSpan"),
        Some("Element 14"),
        Some("Pycon"),
        Some("Saifun Semiconductors"),
        Some("Sibyte Incorporated"),
        Some("MetaLink Technologies"),
        Some("Feiya Technology"),
        Some("I & C Technology"),
        Some("Shikatronics"),
        Some("Elektrobit"),
        Some("Megic"),
        Some("Com-Tier"),
        Some("Malaysia Micro Solutions"),
        Some("Hyperchip"),
        Some("Gemstone Communications"),
        Some("Anadigm (Anadyne)"),
        Some("3ParData"),
        Some("Mellanox Technologies"),
        Some("Tenx Technologies"),
        Some("Helix AG"),
        Some("Domosys"),
        Some("Skyup Technology"),
        Some("HiNT Corporation"),
        Some("Chiaro"),
        Some("MDT Technologies GmbH"),
        Some("Exbit Technology A/S"),
        Some("Integrated Technology Express"),
        Some("AVED Memory"),
        Some("Legerity"),
        Some("Jasmine Networks"),
        Some("Caspian Networks"),
        Some("nCUBE"),
        Some("Silicon Access Networks"),
        Some("FDK Corporation"),
        Some("High Bandwidth Access"),
        Some("MultiLink Technology"),
        Some("BRECIS"),
        Some("World Wide Packets"),
        Some("APW"),
        Some("Chicory Systems"),
        Some("Xstream Logic"),
        Some("Fast-Chip"),
        Some("Zucotto Wireless"),
        Some("Realchip"),
        Some("Galaxy Power"),
        Some("eSilicon"),
        Some("Morphics Technology"),
        Some("Accelerant Networks"),
        Some("Silicon Wave"),
        Some("SandCraft"),
        Some("Elpida"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Solectron"),
        Some("Optosys Technologies"),
        Some("Buffalo (Formerly Melco)"),
        Some("TriMedia Technologies"),
        Some("Cyan Technologies"),
        Some("Global Locate"),
        Some("Optillion"),
        Some("Terago Communications"),
        Some("Ikanos Communications"),
        Some("Princeton Technology"),
        Some("Nanya Technology"),
        Some("Elite Flash Storage"),
        Some("Mysticom"),
        Some("LightSand Communications"),
        Some("ATI Technologies"),
        Some("Agere Systems"),
        Some("NeoMagic"),
        Some("AuroraNetics"),
        Some("Golden Empire"),
        Some("Mushkin"),
        Some("Tioga Technologies"),
        Some("Netlist"),
        Some("TeraLogic"),
        Some("Cicada Semiconductor"),
        Some("Centon Electronics"),
        Some("Tyco Electronics"),
        Some("Magis Works"),
        Some("Zettacom"),
        Some("Cogency Semiconductor"),
        Some("Chipcon AS"),
        Some("Aspex Technology"),
        Some("F5 Networks"),
        Some("Programmable Silicon Solutions"),
        Some("ChipWrights"),
        Some("Acorn Networks"),
        Some("Quicklogic"),
        Some("Kingmax Semiconductor"),
        Some("BOPS"),
        Some("Flasys"),
        Some("BitBlitz Communications"),
        Some("eMemory Technology"),
        Some("Procket Networks"),
        Some("Purple Ray"),
        Some("Trebia Networks"),
        Some("Delta Electronics"),
        Some("Onex Communications"),
        Some("Ample Communications"),
        Some("Memory Experts Intl"),
        Some("Astute Networks"),
        Some("Azanda Network Devices"),
        Some("Dibcom"),
        Some("Tekmos"),
        Some("API NetWorks"),
        Some("Bay Microsystems"),
        Some("Firecron Ltd"),
        Some("Resonext Communications"),
        Some("Tachys Technologies"),
        Some("Equator Technology"),
        Some("Concept Computer"),
        Some("SILCOM"),
        Some("3Dlabs"),
        Some("c’t Magazine"),
        Some("Sanera Systems"),
        Some("Silicon Packets"),
        Some("Viasystems Group"),
        Some("Simtek"),
        Some("Semicon Devices Singapore"),
        Some("Satron Handelsges"),
        Some("Improv Systems"),
        Some("INDUSYS GmbH"),
        Some("Corrent"),
        Some("Infrant Technologies"),
        Some("Ritek Corp"),
        Some("empowerTel Networks"),
        Some("Hypertec"),
        Some("Cavium Networks"),
        Some("PLX Technology"),
        Some("Massana Design"),
        Some("Intrinsity"),
        Some("Valence Semiconductor"),
        Some("Terawave Communications"),
        Some("IceFyre Semiconductor"),
        Some("Primarion"),
        Some("Picochip Designs Ltd"),
        Some("Silverback Systems"),
        Some("Jade Star Technologies"),
        Some("Pijnenburg Securealink"),
        Some("takeMS - Ultron AG"),
        Some("Cambridge Silicon Radio"),
        Some("Swissbit"),
        Some("Nazomi Communications"),
        Some("eWave System"),
        Some("Rockwell Collins"),
        Some("Picocel Co Ltd (Paion)"),
        Some("Alphamosaic Ltd"),
        Some("Sandburst"),
        Some("SiCon Video"),
        Some("NanoAmp Solutions"),
        Some("Ericsson Technology"),
        Some("PrairieComm"),
        Some("Mitac International"),
        Some("Layer N Networks"),
        Some("MtekVision (Atsana)"),
        Some("Allegro Networks"),
        Some("Marvell Semiconductors"),
        Some("Netergy Microelectronic"),
        Some("NVIDIA"),
        Some("Internet Machines"),
        Some("Memorysolution GmbH"),
        Some("Litchfield Communication"),
        Some("Accton Technology"),
        Some("Teradiant Networks"),
        Some("Scaleo Chip"),
        Some("Cortina Systems"),
        Some("RAM Components"),
        Some("Raqia Networks"),
        Some("ClearSpeed"),
        Some("Matsushita Battery"),
        Some("Xelerated"),
        Some("SimpleTech"),
        Some("Utron Technology"),
        Some("Astec International"),
        Some("AVM gmbH"),
        Some("Redux Communications"),
        Some("Dot Hill Systems"),
        Some("TeraChip"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("T-RAM Incorporated"),
        Some("Innovics Wireless"),
        Some("Teknovus"),
        Some("KeyEye Communications"),
        Some("Runcom Technologies"),
        Some("RedSwitch"),
        Some("Dotcast"),
        Some("Silicon Mountain Memory"),
        Some("Signia Technologies"),
        Some("Pixim"),
        Some("Galazar Networks"),
        Some("White Electronic Designs"),
        Some("Patriot Scientific"),
        Some("Neoaxiom Corporation"),
        Some("3Y Power Technology"),
        Some("Scaleo Chip"),
        Some("Potentia Power Systems"),
        Some("C-guys Incorporated"),
        Some("Digital Communications Technology Inc"),
        Some("Silicon-Based Technology"),
        Some("Fulcrum Microsystems"),
        Some("Positivo Informatica Ltd"),
        Some("XIOtech Corporation"),
        Some("PortalPlayer"),
        Some("Zhiying Software"),
        Some("ParkerVision Inc"),
        Some("Phonex Broadband"),
        Some("Skyworks Solutions"),
        Some("Entropic Communications"),
        Some("I’M Intelligent Memory Ltd"),
        Some("Zensys A/S"),
        Some("Legend Silicon Corp"),
        Some("Sci-worx GmbH"),
        Some("SMSC (Standard Microsystems)"),
        Some("Renesas Electronics"),
        Some("Raza Microelectronics"),
        Some("Phyworks"),
        Some("MediaTek"),
        Some("Non-cents Productions"),
        Some("US Modular"),
        Some("Wintegra Ltd"),
        Some("Mathstar"),
        Some("StarCore"),
        Some("Oplus Technologies"),
        Some("Mindspeed"),
        Some("Just Young Computer"),
        Some("Radia Communications"),
        Some("OCZ"),
        Some("Emuzed"),
        Some("LOGIC Devices"),
        Some("Inphi Corporation"),
        Some("Quake Technologies"),
        Some("Vixel"),
        Some("SolusTek"),
        Some("Kongsberg Maritime"),
        Some("Faraday Technology"),
        Some("Altium Ltd"),
        Some("Insyte"),
        Some("ARM Ltd"),
        Some("DigiVision"),
        Some("Vativ Technologies"),
        Some("Endicott Interconnect Technologies"),
        Some("Pericom"),
        Some("Bandspeed"),
        Some("LeWiz Communications"),
        Some("CPU Technology"),
        Some("Ramaxel Technology"),
        Some("DSP Group"),
        Some("Axis Communications"),
        Some("Legacy Electronics"),
        Some("Chrontel"),
        Some("Powerchip Semiconductor"),
        Some("MobilEye Technologies"),
        Some("Excel Semiconductor"),
        Some("A-DATA Technology"),
        Some("VirtualDigm"),
        Some("G Skill Intl"),
        Some("Quanta Computer"),
        Some("Yield Microelectronics"),
        Some("Afa Technologies"),
        Some("KINGBOX Technology Co Ltd"),
        Some("Ceva"),
        Some("iStor Networks"),
        Some("Advance Modules"),
        Some("Microsoft"),
        Some("Open-Silicon"),
        Some("Goal Semiconductor"),
        Some("ARC International"),
        Some("Simmtec"),
        Some("Metanoia"),
        Some("Key Stream"),
        Some("Lowrance Electronics"),
        Some("Adimos"),
        Some("SiGe Semiconductor"),
        Some("Fodus Communications"),
        Some("Credence Systems Corp"),
        Some("Genesis Microchip Inc"),
        Some("Vihana Inc"),
        Some("WIS Technologies"),
        Some("GateChange Technologies"),
        Some("High Density Devices AS"),
        Some("Synopsys"),
        Some("Gigaram"),
        Some("Enigma Semiconductor Inc"),
        Some("Century Micro Inc"),
        Some("Icera Semiconductor"),
        Some("Mediaworks Integrated Systems"),
        Some("O’Neil Product Development"),
        Some("Supreme Top Technology Ltd"),
        Some("MicroDisplay Corporation"),
        Some("Team Group Inc"),
        Some("Sinett Corporation"),
        Some("Toshiba Corporation"),
        Some("Tensilica"),
        Some("SiRF Technology"),
        Some("Bacoc Inc"),
        Some("SMaL Camera Technologies"),
        Some("Thomson SC"),
        Some("Airgo Networks"),
        Some("Wisair Ltd"),
        Some("SigmaTel"),
        Some("Arkados"),
        Some("Compete IT gmbH Co KG"),
        Some("Eudar Technology Inc"),
        Some("Focus Enhancements"),
        Some("Xyratex"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Specular Networks"),
        Some("Patriot Memory (PDP Systems)"),
        Some("U-Chip Technology Corp"),
        Some("Silicon Optix"),
        Some("Greenfield Networks"),
        Some("CompuRAM GmbH"),
        Some("Stargen Inc"),
        Some("NetCell Corporation"),
        Some("Excalibrus Technologies Ltd"),
        Some("SCM Microsystems"),
        Some("Xsigo Systems Inc"),
        Some("CHIPS & Systems Inc"),
        Some("Tier 1 Multichip Solutions"),
        Some("CWRL Labs"),
        Some("Teradici"),
        Some("Gigaram Inc"),
        Some("g2 Microsystems"),
        Some("PowerFlash Semiconductor"),
        Some("P.A. Semi Inc"),
        Some("NovaTech Solutions S.A."),
        Some("c2 Microsystems Inc"),
        Some("Level5 Networks"),
        Some("COS Memory AG"),
        Some("Innovasic Semiconductor"),
        Some("02IC Co Ltd"),
        Some("Tabula Inc"),
        Some("Crucial Technology"),
        Some("Chelsio Communications"),
        Some("Solarflare Communications"),
        Some("Xambala Inc"),
        Some("EADS Astrium"),
        Some("Terra Semiconductor Inc"),
        Some("Imaging Works Inc"),
        Some("Astute Networks Inc"),
        Some("Tzero"),
        Some("Emulex"),
        Some("Power-One"),
        Some("Pulse~LINK Inc"),
        Some("Hon Hai Precision Industry"),
        Some("White Rock Networks Inc"),
        Some("Telegent Systems USA Inc"),
        Some("Atrua Technologies Inc"),
        Some("Acbel Polytech Inc"),
        Some("eRide Inc"),
        Some("ULi Electronics Inc"),
        Some("Magnum Semiconductor Inc"),
        Some("neoOne Technology Inc"),
        Some("Connex Technology Inc"),
        Some("Stream Processors Inc"),
        Some("Focus Enhancements"),
        Some("Telecis Wireless Inc"),
        Some("uNav Microelectronics"),
        Some("Tarari Inc"),
        Some("Ambric Inc"),
        Some("Newport Media Inc"),
        Some("VMTS"),
        Some("Enuclia Semiconductor Inc"),
        Some("Virtium Technology Inc"),
        Some("Solid State System Co Ltd"),
        Some("Kian Tech LLC"),
        Some("Artimi"),
        Some("Power Quotient International"),
        Some("Avago Technologies"),
        Some("ADTechnology"),
        Some("Sigma Designs"),
        Some("SiCortex Inc"),
        Some("Ventura Technology Group"),
        Some("eASIC"),
        Some("M.H.S. SAS"),
        Some("Micro Star International"),
        Some("Rapport Inc"),
        Some("Makway International"),
        Some("Broad Reach Engineering Co"),
        Some("Semiconductor Mfg Intl Corp"),
        Some("SiConnect"),
        Some("FCI USA Inc"),
        Some("Validity Sensors"),
        Some("Coney Technology Co Ltd"),
        Some("Spans Logic"),
        Some("Neterion Inc"),
        Some("Qimonda"),
        Some("New Japan Radio Co Ltd"),
        Some("Velogix"),
        Some("Montalvo Systems"),
        Some("iVivity Inc"),
        Some("Walton Chaintech"),
        Some("AENEON"),
        Some("Lorom Industrial Co Ltd"),
        Some("Radiospire Networks"),
        Some("Sensio Technologies Inc"),
        Some("Nethra Imaging"),
        Some("Hexon Technology Pte Ltd"),
        Some("CompuStocx (CSX)"),
        Some("Methode Electronics Inc"),
        Some("Connect One Ltd"),
        Some("Opulan Technologies"),
        Some("Septentrio NV"),
        Some("Goldenmars Technology Inc"),
        Some("Kreton Corporation"),
        Some("Cochlear Ltd"),
        Some("Altair Semiconductor"),
        Some("NetEffect Inc"),
        Some("Spansion Inc"),
        Some("Taiwan Semiconductor Mfg"),
        Some("Emphany Systems Inc"),
        Some("ApaceWave Technologies"),
        Some("Mobilygen Corporation"),
        Some("Tego"),
        Some("Cswitch Corporation"),
        Some("Haier (Beijing) IC Design Co"),
        Some("MetaRAM"),
        Some("Axel Electronics Co Ltd"),
        Some("Tilera Corporation"),
        Some("Aquantia"),
        Some("Vivace Semiconductor"),
        Some("Redpine Signals"),
        Some("Octalica"),
        Some("InterDigital Communications"),
        Some("Avant Technology"),
        Some("Asrock Inc"),
        Some("Availink"),
        Some("Quartics Inc"),
        Some("Element CXI"),
        Some("Innovaciones Microelectronicas"),
        Some("VeriSilicon Microelectronics"),
        Some("W5 Networks"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("MOVEKING"),
        Some("Mavrix Technology Inc"),
        Some("CellGuide Ltd"),
        Some("Faraday Technology"),
        Some("Diablo Technologies Inc"),
        Some("Jennic"),
        Some("Octasic"),
        Some("Molex Incorporated"),
        Some("3Leaf Networks"),
        Some("Bright Micron Technology"),
        Some("Netxen"),
        Some("NextWave Broadband Inc"),
        Some("DisplayLink"),
        Some("ZMOS Technology"),
        Some("Tec-Hill"),
        Some("Multigig Inc"),
        Some("Amimon"),
        Some("Euphonic Technologies Inc"),
        Some("BRN Phoenix"),
        Some("InSilica"),
        Some("Ember Corporation"),
        Some("Avexir Technologies Corporation"),
        Some("Echelon Corporation"),
        Some("Edgewater Computer Systems"),
        Some("XMOS Semiconductor Ltd"),
        Some("GENUSION Inc"),
        Some("Memory Corp NV"),
        Some("SiliconBlue Technologies"),
        Some("Rambus Inc"),
        Some("Andes Technology Corporation"),
        Some("Coronis Systems"),
        Some("Achronix Semiconductor"),
        Some("Siano Mobile Silicon Ltd"),
        Some("Semtech Corporation"),
        Some("Pixelworks Inc"),
        Some("Gaisler Research AB"),
        Some("Teranetics"),
        Some("Toppan Printing Co Ltd"),
        Some("Kingxcon"),
        Some("Silicon Integrated Systems"),
        Some("I-O Data Device Inc"),
        Some("NDS Americas Inc"),
        Some("Solomon Systech Limited"),
        Some("On Demand Microelectronics"),
        Some("Amicus Wireless Inc"),
        Some("SMARDTV SNC"),
        Some("Comsys Communication Ltd"),
        Some("Movidia Ltd"),
        Some("Javad GNSS Inc"),
        Some("Montage Technology Group"),
        Some("Trident Microsystems"),
        Some("Super Talent"),
        Some("Optichron Inc"),
        Some("Future Waves UK Ltd"),
        Some("SiBEAM Inc"),
        Some("InicoreInc"),
        Some("Virident Systems"),
        Some("M2000 Inc"),
        Some("ZeroG Wireless Inc"),
        Some("Gingle Technology Co Ltd"),
        Some("Space Micro Inc"),
        Some("Wilocity"),
        Some("Novafora Inc"),
        Some("iKoa Corporation"),
        Some("ASint Technology"),
        Some("Ramtron"),
        Some("Plato Networks Inc"),
        Some("IPtronics AS"),
        Some("Infinite-Memories"),
        Some("Parade Technologies Inc"),
        Some("Dune Networks"),
        Some("GigaDevice Semiconductor"),
        Some("Modu Ltd"),
        Some("CEITEC"),
        Some("Northrop Grumman"),
        Some("XRONET Corporation"),
        Some("Sicon Semiconductor AB"),
        Some("Atla Electronics Co Ltd"),
        Some("TOPRAM Technology"),
        Some("Silego Technology Inc"),
        Some("Kinglife"),
        Some("Ability Industries Ltd"),
        None,
        Some("Augusta Technology Inc"),
        Some("Nantronics Semiconductors"),
        Some("Hilscher Gesellschaft"),
        Some("Quixant Ltd"),
        Some("Percello Ltd"),
        Some("NextIO Inc"),
        Some("Scanimetrics Inc"),
        Some("FS-Semi Company Ltd"),
        Some("Infinera Corporation"),
        Some("SandForce Inc"),
        Some("Lexar Media"),
        Some("Teradyne Inc"),
        Some("Memory Exchange Corp"),
        Some("Suzhou Smartek Electronics"),
        Some("Avantium Corporation"),
        Some("ATP Electronics Inc"),
        Some("Valens Semiconductor Ltd"),
        Some("Agate Logic Inc"),
        Some("Netronome"),
        Some("Zenverge Inc"),
        Some("N-trig Ltd"),
        Some("SanMax Technologies Inc"),
        Some("Contour Semiconductor Inc"),
        Some("TwinMOS"),
        Some("Silicon Systems Inc"),
        Some("V-Color Technology Inc"),
        Some("Certicom Corporation"),
        Some("JSC ICC Milandr"),
        Some("PhotoFast Global Inc"),
        Some("InnoDisk Corporation"),
        Some("Muscle Power"),
        Some("Energy Micro"),
        Some("Innofidei"),
        Some("CopperGate Communications"),
        Some("Holtek Semiconductor Inc"),
        Some("Myson Century Inc"),
        Some("FIDELIX"),
        Some("Red Digital Cinema"),
        Some("Densbits Technology"),
        Some("Zempro"),
        Some("MoSys"),
        Some("Provigent"),
        Some("Triad Semiconductor Inc"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Siklu Communication Ltd"),
        Some("A Force Manufacturing Ltd"),
        Some("Strontium"),
        Some("ALi Corp (Abilis Systems)"),
        Some("Siglead Inc"),
        Some("Ubicom Inc"),
        Some("Unifosa Corporation"),
        Some("Stretch Inc"),
        Some("Lantiq Deutschland GmbH"),
        Some("Visipro."),
        Some("EKMemory"),
        Some("Microelectronics Institute ZTE"),
        Some("u-blox AG"),
        Some("Carry Technology Co Ltd"),
        Some("Nokia"),
        Some("King Tiger Technology"),
        Some("Sierra Wireless"),
        Some("HT Micron"),
        Some("Albatron Technology Co Ltd"),
        Some("Leica Geosystems AG"),
        Some("BroadLight"),
        Some("AEXEA"),
        Some("ClariPhy Communications Inc"),
        Some("Green Plug"),
        Some("Design Art Networks"),
        Some("Mach Xtreme Technology Ltd"),
        Some("ATO Solutions Co Ltd"),
        Some("Ramsta"),
        Some("Greenliant Systems Ltd"),
        Some("Teikon"),
        Some("Antec Hadron"),
        Some("NavCom Technology Inc"),
        Some("Shanghai Fudan Microelectronics"),
        Some("Calxeda Inc"),
        Some("JSC EDC Electronics"),
        Some("Kandit Technology Co Ltd"),
        Some("Ramos Technology"),
        Some("Goldenmars Technology"),
        Some("XeL Technology Inc"),
        Some("Newzone Corporation"),
        Some("ShenZhen MercyPower Tech"),
        Some("Nanjing Yihuo Technology"),
        Some("Nethra Imaging Inc"),
        Some("SiTel Semiconductor BV"),
        Some("SolidGear Corporation"),
        Some("Topower Computer Ind Co Ltd"),
        Some("Wilocity"),
        Some("Profichip GmbH"),
        Some("Gerad Technologies"),
        Some("Ritek Corporation"),
        Some("Gomos Technology Limited"),
        Some("Memoright Corporation"),
        Some("D-Broad Inc"),
        Some("HiSilicon Technologies"),
        Some("Syndiant Inc."),
        Some("Enverv Inc"),
        Some("Cognex"),
        Some("Xinnova Technology Inc"),
        Some("Ultron AG"),
        Some("Concord Idea Corporation"),
        Some("AIM Corporation"),
        Some("Lifetime Memory Products"),
        Some("Ramsway"),
        Some("Recore Systems B.V."),
        Some("Haotian Jinshibo Science Tech"),
        Some("Being Advanced Memory"),
        Some("Adesto Technologies"),
        Some("Giantec Semiconductor Inc"),
        Some("HMD Electronics AG"),
        Some("Gloway International (HK)"),
        Some("Kingcore"),
        Some("Anucell Technology Holding"),
        Some("Accord Software & Systems Pvt. Ltd"),
        Some("Active-Semi Inc"),
        Some("Denso Corporation"),
        Some("TLSI Inc"),
        Some("Qidan"),
        Some("Mustang"),
        Some("Orca Systems"),
        Some("Passif Semiconductor"),
        None,
        Some("Memphis Electronic"),
        Some("Beckhoff Automation GmbH"),
        Some("Harmony Semiconductor Corp"),
        Some("Air Computers SRL"),
        Some("TMT Memory"),
        Some("Eorex Corporation"),
        Some("Xingtera"),
        Some("Netsol"),
        Some("Bestdon Technology Co Ltd"),
        Some("Baysand Inc"),
        Some("Uroad Technology Co Ltd"),
        Some("Wilk Elektronik S.A."),
        Some("AAI"),
        Some("Harman"),
        Some("Berg Microelectronics Inc"),
        Some("ASSIA Inc"),
        Some("Visiontek Products LLC"),
        Some("OCMEMORY"),
        Some("Welink Solution Inc"),
        Some("Shark Gaming"),
        Some("Avalanche Technology"),
        Some("R&D Center ELVEES OJSC"),
        Some("KingboMars Technology Co Ltd"),
        None,
        Some("Transcend Technology Co Ltd"),
        Some("Everspin Technologies"),
        Some("Hon-Hai Precision"),
        Some("Smart Storage Systems"),
        Some("Toumaz Group"),
        Some("Zentel Electronics Corporation"),
        Some("Panram International Corporation"),
        Some("Silicon Space Technology"),
        Some("LITE-ON IT Corporation"),
        Some("Inuitive"),
        Some("HMicro"),
        Some("BittWare Inc"),
        Some("GLOBALFOUNDRIES"),
        Some("ACPI Digital Co Ltd"),
        Some("Annapurna Labs"),
        Some("AcSiP Technology Corporation"),
        Some("Idea! Electronic Systems"),
        Some("Gowe Technology Co Ltd"),
        Some("Hermes Testing Solutions Inc"),
        Some("Positivo BGH"),
        Some("Intelligence  Silicon Technology"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("3D PLUS"),
        Some("Diehl Aerospace"),
        Some("Fairchild"),
        Some("Mercury Systems"),
        Some("Sonics Inc"),
        Some("Emerson Machine Automation"),
        Some("Shenzhen Jinge Information Co Ltd"),
        Some("SCWW"),
        Some("Silicon Motion Inc"),
        Some("Anurag"),
        Some("King Kong"),
        Some("FROM30 Co Ltd"),
        Some("Gowin Semiconductor Corp"),
        Some("Fremont Micro Devices Ltd"),
        Some("Ericsson Modems"),
        Some("Exelis"),
        Some("Satixfy Ltd"),
        Some("Galaxy Microsystems Ltd"),
        Some("Gloway International Co Ltd"),
        Some("Lab"),
        Some("Smart Energy Instruments"),
        Some("Approved Memory Corporation"),
        Some("Axell Corporation"),
        Some("Essencore Limited"),
        Some("Phytium"),
        Some("Xi’an UnilC Semiconductors Co Ltd"),
        Some("Ambiq Micro"),
        Some("eveRAM Technology Inc"),
        Some("Infomax"),
        Some("Butterfly Network Inc"),
        Some("Shenzhen City Gcai Electronics"),
        Some("Stack Devices Corporation"),
        Some("ADK Media Group"),
        Some("TSP Global Co Ltd"),
        Some("HighX"),
        Some("Shenzhen Elicks Technology"),
        Some("ISSI/Chingis"),
        Some("Google Inc"),
        Some("Dasima International Development"),
        Some("Leahkinn Technology Limited"),
        Some("HIMA Paul Hildebrandt GmbH Co KG"),
        Some("Keysight Technologies"),
        Some("Techcomp International (Fastable)"),
        Some("Ancore Technology Corporation"),
        Some("Nuvoton"),
        Some("Korea Uhbele International Group Ltd"),
        Some("Ikegami Tsushinki Co Ltd"),
        Some("RelChip Inc"),
        Some("Baikal Electronics"),
        Some("Nemostech Inc"),
        Some("Memorysolution GmbH"),
        Some("Silicon Integrated Systems Corporation"),
        Some("Xiede"),
        Some("BRC"),
        Some("Flash Chi"),
        Some("Jone"),
        Some("GCT Semiconductor Inc"),
        Some("Hong Kong Zetta Device Technology"),
        Some("Unimemory Technology(s) Pte Ltd"),
        Some("Cuso"),
        Some("Kuso"),
        Some("Uniquify Inc"),
        Some("Skymedi Corporation"),
        Some("Core Chance Co Ltd"),
        Some("Tekism Co Ltd"),
        Some("Seagate Technology PLC"),
        Some("Hong Kong Gaia Group Co Limited"),
        Some("Gigacom Semiconductor LLC"),
        Some("V2 Technologies"),
        Some("TLi"),
        Some("Neotion"),
        Some("Lenovo"),
        Some("Shenzhen Zhongteng Electronic Corp Ltd"),
        Some("Compound Photonics"),
        Some("in2H2 inc"),
        Some("Shenzhen Pango Microsystems Co Ltd"),
        Some("Vasekey"),
        None,
        Some("Eyenix Co Ltd"),
        Some("Heoriady"),
        Some("Accelerated Memory Production Inc"),
        Some("INVECAS Inc"),
        Some("AP Memory"),
        Some("Douqi Technology"),
        Some("Etron Technology Inc"),
        Some("Indie Semiconductor"),
        Some("Socionext Inc"),
        Some("HGST"),
        Some("EVGA"),
        Some("Audience Inc"),
        Some("EpicGear"),
        Some("Vitesse Enterprise Co"),
        Some("Foxtronn International Corporation"),
        Some("Bretelon Inc"),
        Some("Graphcore"),
        Some("Eoplex Inc"),
        Some("MaxLinear Inc"),
        Some("ETA Devices"),
        Some("LOKI"),
        Some("IMS Electronics Co Ltd"),
        Some("Dosilicon Co Ltd"),
        Some("Dolphin Integration"),
        Some("Shenzhen Mic Electronics Technolog"),
        Some("Boya Microelectronics Inc"),
        Some("Geniachip (Roche)"),
        Some("Axign"),
        Some("Kingred Electronic Technology Ltd"),
        Some("Chao Yue Zhuo Computer Business Dept."),
        None,
        Some("Crocus Technology Inc"),
        Some("Creative Chips GmbH"),
        Some("GE Aviation Systems LLC."),
        Some("Asgard"),
        Some("Good Wealth Technology Ltd"),
        Some("TriCor Technologies"),
        Some("Nova-Systems GmbH"),
        Some("JUHOR"),
        Some("Zhuhai Douke Commerce Co Ltd"),
        Some("DSL Memory"),
        Some("Anvo-Systems Dresden GmbH"),
        Some("Realtek"),
        Some("AltoBeam"),
        Some("Wave Computing"),
        Some("Beijing TrustNet Technology Co Ltd"),
        Some("Innovium Inc"),
        Some("Starsway Technology Limited"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Weltronics Co LTD"),
        Some("VMware Inc"),
        Some("Hewlett Packard Enterprise"),
        Some("INTENSO"),
        Some("Puya Semiconductor"),
        Some("MEMORFI"),
        Some("MSC Technologies GmbH"),
        Some("Txrui"),
        Some("SiFive Inc"),
        Some("Spreadtrum Communications"),
        Some("XTX Technology Limited"),
        Some("UMAX Technology"),
        Some("Shenzhen Yong Sheng Technology"),
        Some("SNOAMOO (Shenzhen Kai Zhuo Yue)"),
        Some("Daten Tecnologia LTDA"),
        Some("Shenzhen XinRuiYan Electronics"),
        Some("Eta Compute"),
        Some("Energous"),
        Some("Raspberry Pi Trading Ltd"),
        Some("Shenzhen Chixingzhe Tech Co Ltd"),
        Some("Silicon Mobility"),
        Some("IQ-Analog Corporation"),
        Some("Uhnder Inc"),
        Some("Impinj"),
        Some("DEPO Computers"),
        Some("Nespeed Sysems"),
        Some("Yangtze Memory Technologies Co Ltd"),
        Some("MemxPro Inc"),
        Some("Tammuz Co Ltd"),
        Some("Allwinner Technology"),
        None,
        Some("XMC"),
        Some("Teclast"),
        Some("Maxsun"),
        Some("Haiguang Integrated Circuit Design"),
        Some("RamCENTER Technology"),
        Some("Phison Electronics Corporation"),
        Some("Guizhou Huaxintong Semi-Conductor"),
        Some("Network Intelligence"),
        Some("Continental Technology (Holdings)"),
        Some("Guangzhou Huayan Suning Electronic"),
        Some("Guangzhou Zhouji Electronic Co Ltd"),
        Some("Shenzhen Giant Hui Kang Tech Co Ltd"),
        Some("Shenzhen Yilong Innovative Co Ltd"),
        Some("Neo Forza"),
        Some("Lyontek Inc"),
        Some("Shanghai Kuxin Microelectronics Ltd"),
        Some("Shenzhen Larix Technology Co Ltd"),
        Some("Qbit Semiconductor Ltd"),
        Some("Insignis Technology Corporation"),
        Some("Lanson Memory Co Ltd"),
        Some("Shenzhen Superway Electronics Co Ltd"),
        Some("Canaan-Creative Co Ltd"),
        Some("Black Diamond Memory"),
        Some("Shenzhen City Parker Baking Electronics"),
        Some("Shenzhen Baihong Technology Co Ltd"),
        Some("GEO Semiconductors"),
        Some("OCPC"),
        Some("Artery Technology Co Ltd"),
        Some("Jinyu"),
        Some("ShenzhenYing Chi Technology Development"),
        Some("Shenzhen Pengcheng Xin Technology"),
        Some("Pegasus Semiconductor (Shanghai) Co"),
        Some("Mythic Inc"),
        Some("Elmos Semiconductor AG"),
        Some("Kllisre"),
        Some("Shenzhen Winconway Technology"),
        Some("Shenzhen Xingmem Technology Corp"),
        Some("Gold Key Technology Co Ltd"),
        Some("Habana Labs Ltd"),
        Some("Hoodisk Electronics Co Ltd"),
        Some("SemsoTai (SZ) Technology Co Ltd"),
        Some("OM Nanotech Pvt. Ltd"),
        Some("Shenzhen Zhifeng Weiye Technology"),
        Some("Xinshirui (Shenzhen) Electronics Co"),
        Some("Guangzhou Zhong Hao Tian Electronic"),
        Some("Shenzhen Longsys Electronics Co Ltd"),
        Some("Deciso B.V."),
        Some("Puya Semiconductor (Shenzhen)"),
        Some("Shenzhen Veineda Technology Co Ltd"),
        Some("Antec Memory"),
        Some("Cortus SAS"),
        Some("Dust Leopard"),
        Some("MyWo AS"),
        Some("J&A Information Inc"),
        Some("Shenzhen JIEPEI Technology Co Ltd"),
        Some("Heidelberg University"),
        Some("Flexxon PTE Ltd"),
        Some("Wiliot"),
        Some("Raysun Electronics International Ltd"),
        Some("Aquarius Production Company LLC"),
        Some("MACNICA DHW LTDA"),
        Some("Intelimem"),
        Some("Zbit Semiconductor Inc"),
        Some("Shenzhen Technology Co Ltd"),
        Some("Signalchip"),
        Some("Shenzen Recadata Storage Technology"),
        Some("Hyundai Technology"),
        Some("Shanghai Fudi Investment Development"),
        Some("Aixi Technology"),
        Some("Tecon MT"),
        Some("Onda Electric Co Ltd"),
        Some("Jinshen"),
        Some("Kimtigo Semiconductor (HK) Limited"),
        Some("IIT Madras"),
        Some("Shenshan (Shenzhen) Electronic"),
        Some("Hefei Core Storage Electronic Limited"),
        Some("Colorful Technology Ltd"),
        Some("Visenta (Xiamen) Technology Co Ltd"),
        Some("Roa Logic BV"),
        Some("NSITEXE Inc"),
        Some("Hong Kong Hyunion Electronics"),
        Some("ASK Technology Group Limited"),
        Some("GIGA-BYTE Technology Co Ltd"),
        Some("Terabyte Co Ltd"),
        Some("Hyundai Inc"),
        Some("EXCELERAM"),
        Some("PsiKick"),
        Some("Netac Technology Co Ltd"),
        Some("PCCOOLER"),
        Some("Jiangsu Huacun Electronic Technology"),
        Some("Shenzhen Micro Innovation Industry"),
        Some("Beijing Tongfang Microelectronics Co"),
        Some("XZN Storage Technology"),
        Some("ChipCraft Sp. z.o.o."),
        Some("ALLFLASH Technology Limited"),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        None,
        Some("Foerd Technology Co Ltd"),
        Some("KingSpec"),
        Some("Codasip Ltd"),
        Some("SL Link Co Ltd"),
        Some("Shenzhen Kefu Technology Co Limited"),
        Some("Shenzhen ZST Electronics Technology"),
        Some("Kyokuto Electronic Inc"),
        Some("Warrior Technology"),
        Some("TRINAMIC Motion Control GmbH & Co"),
        Some("PixelDisplay Inc"),
        Some("Shenzhen Futian District Bo Yueda Elec"),
        Some("Richtek Power"),
        Some("Shenzhen LianTeng Electronics Co Ltd"),
        Some("AITC Memory"),
        Some("UNIC Memory Technology Co Ltd"),
        Some("Shenzhen Huafeng Science Technology"),
        Some("ChangXin Memory Technologies Inc"),
        None,
        Some("SambaNova Systems"),
        Some("V-GEN"),
        Some("Jump Trading"),
        Some("Ampere Computing"),
        Some("Shenzhen Zhongshi Technology Co Ltd"),
        Some("Shenzhen Zhongtian Bozhong Technology"),
        Some("Tri-Tech International"),
        Some("Silicon Intergrated Systems Corporation"),
        Some("Shenzhen HongDingChen Information"),
        Some("Plexton Holdings Limited"),
        Some("AMS (Jiangsu Advanced Memory Semi)"),
        Some("Wuhan Jing Tian Interconnected Tech Co"),
        Some("Axia Memory Technology"),
        Some("Chipset Technology Holding Limited"),
        Some("Shenzhen Xinshida Technology Co Ltd"),
        Some("Shenzhen Chuangshifeida Technology"),
        Some("Guangzhou MiaoYuanJi Technology"),
        Some("ADVAN Inc"),
        None,
        Some("Guangzhou Guang Xie Cheng Trading"),
        Some("StarRam International Co Ltd"),
        Some("Shen Zhen XinShenHua Tech Co Ltd"),
        Some("UltraMemory Inc"),
        Some("New Coastline Global Tech Industry Co"),
        Some("Sinker"),
        Some("Diamond"),
        Some("PUSKILL"),
        Some("Guangzhou Hao Jia Ye Technology Co"),
        Some("Ming Xin Limited"),
        Some("Barefoot Networks"),
        Some("Biwin Semiconductor (HK) Co Ltd"),
        Some("UD INFO Corporation"),
        Some("Trek Technology (S) PTE Ltd"),
        Some("Xiamen Kingblaze Technology Co Ltd"),
        Some("Shenzhen Lomica Technology Co Ltd"),
        Some("Nuclei System Technology Co Ltd"),
        Some("Wuhan Xun Zhan Electronic Technology"),
        Some("Shenzhen Ingacom Semiconductor Ltd"),
        Some("Zotac Technology Ltd"),
        Some("Foxline"),
        Some("Shenzhen Farasia Science Technology"),
        Some("Efinix Inc"),
        Some("Hua Nan San Xian Technology Co Ltd"),
        Some("Goldtech Electronics Co Ltd"),
        Some("Shanghai Han Rong Microelectronics Co"),
        Some("Shenzhen Zhongguang Yunhe Trading"),
        Some("Smart Shine(QingDao) Microelectronics"),
        Some("Thermaltake Technology Co Ltd"),
        Some("Shenzhen O’Yang Maile Technology Ltd"),
        Some("UPMEM"),
        Some("Chun Well Technology Holding Limited"),
        Some("Astera Labs Inc"),
        Some("VMEMORY Co Ltd"),
        Some("Advantech Co Ltd"),
        Some("Chengdu Fengcai Electronic Technology"),
        Some("The Boeing Company"),
        Some("ThinCI Inc"),
        Some("Ramonster Technology Co Ltd"),
        Some("Wuhan Naonongmai Technology Co Ltd"),
        Some("Shenzhen Hui ShingTong Technology"),
        Some("Yourlyon"),
        Some("Fabu Technology"),
        Some("Shenzhen Yikesheng Technology Co Ltd"),
        Some("NOR-MEM"),
        Some("Cervoz Co Ltd"),
        Some("Bitmain Technologies Inc."),
        Some("Facebook Inc"),
        Some("Shenzhen Longsys Electronics Co Ltd"),
        Some("Guangzhou Siye Electronic Technology"),
        Some("Silergy"),
        Some("Adamway"),
        Some("PZG"),
        Some("Shenzhen King Power Electronics"),
        Some("Guangzhou ZiaoFu Tranding Co Ltd"),
        Some("Shenzhen SKIHOTAR Semiconductor"),
        Some("PulseRain Technology"),
        Some("Seeker Technology Limited"),
        Some("Shenzhen OSCOO Tech Co Ltd"),
        Some("Shenzhen Yze Technology Co Ltd"),
        Some("Shenzhen Jieshuo Electronic Commerce"),
        Some("Gazda"),
        Some("Hua Wei Technology Co Ltd"),
        Some("Esperanto Technologies"),
        Some("JinSheng Electronic (Shenzhen) Co Ltd"),
        Some("Shenzhen Shi Bolunshuai Technology"),
        Some("Shanghai Rei Zuan Information Tech"),
        Some("Fraunhofer IIS"),
        Some("Kandou Bus SA"),
        Some("Acer"),
        Some("Artmem Technology Co Ltd"),
        Some("Gstar Semiconductor Co Ltd"),
        Some("ShineDisk"),
        Some("Shenzhen CHN Technology Co Ltd"),
        Some("UnionChip Semiconductor Co Ltd"),
        Some("Tanbassh"),
        Some("Shenzhen Tianyu Jieyun Intl Logistics"),
        Some("MCLogic Inc"),
        Some("Eorex Corporation"),
        Some("Arm Technology (China) Co Ltd"),
        Some("Lexar Co Limited"),
        Some("QinetiQ Group plc"),
        Some("Exascend"),
        Some(""),
        Some(""),
        Some(""),
        Some(""),
        Some(""),
        Some(""),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
];
/// Returns the JEP106 specification version code.
pub const fn version() -> &'static str {
    "JEP106AY"
}
